---
version: "2"
plugins:
  shellcheck:
    enabled: true
  scss-lint:
    enabled: true
  fixme:
    enabled: true
  tslint:
    enabled: true
    config: tslint.codeclimate.json
  nodesecurity:
    enabled: true
exclude_patterns:
- "**/node_modules/"
- "coverage/"
- "dist/"
- "**/font-awesome/"
- "**/*.spec.ts"
