dist: trusty
language: node_js
node_js:
  - '10'
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  ssh_known_hosts: moukari.assembly.org
before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
env:
  - CHROME_BIN=google-chrome-stable
cache: yarn
jobs:
  include:
    - stage: test
      script:
        - yarn test
        - npm run sass-lint
        - '[ "${TRAVIS_PULL_REQUEST}" != "false" ] && travis_terminate 0 || :'
        - '[ "${TRAVIS_BRANCH}" != "master" ] && travis_terminate 0 || :'
        - ./node_modules/.bin/codeclimate-test-reporter < coverage/lcov.info
    - stage: test e2e
      script: yarn e2e
    - stage: build & deploy
      if: branch = master and type in (push)
      script:
        - '[ "${TRAVIS_PULL_REQUEST}" != "false" ] && travis_terminate 0 || :'
        - '[ "${TRAVIS_BRANCH}" != "master" ] && travis_terminate 0 || :'
        - openssl aes-256-cbc -K $encrypted_b9133dc7101e_key -iv $encrypted_b9133dc7101e_iv
          -in deploy.tar.gz.enc -out deploy.tar.gz -d
        - tar zxvf deploy.tar.gz
        - mv deploy/ssh_config ~/.ssh/config
        - mv deploy/deployment_key ~/.ssh/id_rsa
        - chmod 0600 ~/.ssh/*
        - yarn build
        - rsync -avW --delete-before dist/dev/ ${TRAVIS_BRANCH}:/var/www/assembly/dev
        - rsync -avW --delete-before dist/prod/ ${TRAVIS_BRANCH}:/var/www/assembly/stg
notifications:
  slack:
    secure: GmaJWbbIbvQxHV+jSK1V1HGWtEy15MGD7UajsDm5YYxHFH0gqbGEBV6t5TahL/S0feZfMrQwqI+ZpWMOB+pVY404+gLfczredFp4nRuGaum3+BNWQjMVdKqh2Kv851Y8yUsZqg9jeY/C4Sv/gEzzdfek76dnV5/Yl185zEZPC0/dCzekVa60u6i1fBut2ll+I1aQjyY3HlEj6krjaEYx7ptY+xrJWqyf9SkStDvxYEWKX3biGFbhofNLeumimNRN4oGZVOVFCPaLH4Pl7DGvkHlEK05BKJZe+b2YWI+efSPFUt15gcImpf/MDpc+lkYtXuM1nuIRjAU6S4HgQLK2wRv2HXxaAbA0Ar24LzOkKzqJRA/ciyRwKJUUfsN36LH3I0DS+ZJzV5q5PJptrrBge0g1WLzLdUa9YkySTIxFtmOhMNRt5DpAoHXXm98UQPo7gP9tNenYxWurRntjHYOzFmtIKpxB//kPIOFQRoEHjgMM1J1/HxVwQ9LeuYEP37jHroWp/++aCKZJdDN5Ua4WqXnavBlXmSuaWyaTIn8jAZIz4tk0y1PWsgOt/2VC1/TJC4o53HNal5t/kVaQvIzC2FiYNVtN9M4MNhxeEST/VeaG7MgiD3VLNVTPAL79HdxcwFF+7HHLHLHKKoMwZpoJMXCH8iduyjlYnKDzBORtdEc=
