language: node_js

node_js:
  - "8"

cache: yarn

jobs:
  include:
    - script: yarn test
    - script: yarn e2e
    - stage: build
      script: yarn build
    - stage: deploy
      script: echo "Deploying!"
