dist: trusty
language: node_js
node_js:
- '8'
addons:
  chrome: stable
env:
- CHROME_BIN=google-chrome-stable
cache: yarn
before_install:
- openssl aes-256-cbc -K $encrypted_b9133dc7101e_key -iv $encrypted_b9133dc7101e_iv
  -in ssh-key.enc -out ssh-key -d
- mv ssh-key ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa
jobs:
  include:
  - stage: test
    script:
      - yarn test -- --singleRun
      - cat coverage/lcov.info | ./node_modules/.bin/coveralls
  - stage: test
    script: yarn e2e
  - stage: build & deploy
    script:
    - yarn build
    - '[ "$TRAVIS_BRANCH" != "master" ] && travis_terminate 0 || :'
    - rsync -avWe "ssh -o StrictHostKeyChecking=no" --delete-before dist/ asmweb@moukari.assembly.org:/data/httpd/site/neo.assembly.org/html
